#ifndef __wasilibc___errno_values_h
#define __wasilibc___errno_values_h

#include <wasi.h>

#define E2BIG WASI_E2BIG
#define EACCES WASI_EACCES
#define EADDRINUSE WASI_EADDRINUSE
#define EADDRNOTAVAIL WASI_EADDRNOTAVAIL
#define EAFNOSUPPORT WASI_EAFNOSUPPORT
#define EAGAIN WASI_EAGAIN
#define EALREADY WASI_EALREADY
#define EBADF WASI_EBADF
#define EBADMSG WASI_EBADMSG
#define EBUSY WASI_EBUSY
#define ECANCELED WASI_ECANCELED
#define ECHILD WASI_ECHILD
#define ECONNABORTED WASI_ECONNABORTED
#define ECONNREFUSED WASI_ECONNREFUSED
#define ECONNRESET WASI_ECONNRESET
#define EDEADLK WASI_EDEADLK
#define EDESTADDRREQ WASI_EDESTADDRREQ
#define EDOM WASI_EDOM
#define EDQUOT WASI_EDQUOT
#define EEXIST WASI_EEXIST
#define EFAULT WASI_EFAULT
#define EFBIG WASI_EFBIG
#define EHOSTUNREACH WASI_EHOSTUNREACH
#define EIDRM WASI_EIDRM
#define EILSEQ WASI_EILSEQ
#define EINPROGRESS WASI_EINPROGRESS
#define EINTR WASI_EINTR
#define EINVAL WASI_EINVAL
#define EIO WASI_EIO
#define EISCONN WASI_EISCONN
#define EISDIR WASI_EISDIR
#define ELOOP WASI_ELOOP
#define EMFILE WASI_EMFILE
#define EMLINK WASI_EMLINK
#define EMSGSIZE WASI_EMSGSIZE
#define EMULTIHOP WASI_EMULTIHOP
#define ENAMETOOLONG WASI_ENAMETOOLONG
#define ENETDOWN WASI_ENETDOWN
#define ENETRESET WASI_ENETRESET
#define ENETUNREACH WASI_ENETUNREACH
#define ENFILE WASI_ENFILE
#define ENOBUFS WASI_ENOBUFS
#define ENODEV WASI_ENODEV
#define ENOENT WASI_ENOENT
#define ENOEXEC WASI_ENOEXEC
#define ENOLCK WASI_ENOLCK
#define ENOLINK WASI_ENOLINK
#define ENOMEM WASI_ENOMEM
#define ENOMSG WASI_ENOMSG
#define ENOPROTOOPT WASI_ENOPROTOOPT
#define ENOSPC WASI_ENOSPC
#define ENOSYS WASI_ENOSYS
#define ENOTCONN WASI_ENOTCONN
#define ENOTDIR WASI_ENOTDIR
#define ENOTEMPTY WASI_ENOTEMPTY
#define ENOTRECOVERABLE WASI_ENOTRECOVERABLE
#define ENOTSOCK WASI_ENOTSOCK
#define ENOTSUP WASI_ENOTSUP
#define ENOTTY WASI_ENOTTY
#define ENXIO WASI_ENXIO
#define EOVERFLOW WASI_EOVERFLOW
#define EOWNERDEAD WASI_EOWNERDEAD
#define EPERM WASI_EPERM
#define EPIPE WASI_EPIPE
#define EPROTO WASI_EPROTO
#define EPROTONOSUPPORT WASI_EPROTONOSUPPORT
#define EPROTOTYPE WASI_EPROTOTYPE
#define ERANGE WASI_ERANGE
#define EROFS WASI_EROFS
#define ESPIPE WASI_ESPIPE
#define ESRCH WASI_ESRCH
#define ESTALE WASI_ESTALE
#define ETIMEDOUT WASI_ETIMEDOUT
#define ETXTBSY WASI_ETXTBSY
#define EXDEV WASI_EXDEV
#define ENOTCAPABLE WASI_ENOTCAPABLE

#define EOPNOTSUPP ENOTSUP
#define EWOULDBLOCK EAGAIN

#endif
