#ifndef __wasilibc___header_sys_mman_h
#define __wasilibc___header_sys_mman_h

#include <wasi.h>

#define MAP_FAILED ((void *)-1)

#define MAP_ANON __WASI_MAP_ANON
#define MAP_FIXED __WASI_MAP_FIXED
#define MAP_PRIVATE __WASI_MAP_PRIVATE
#define MAP_SHARED __WASI_MAP_SHARED

#define PROT_EXEC __WASI_PROT_EXEC
#define PROT_WRITE __WASI_PROT_WRITE
#define PROT_READ __WASI_PROT_READ

#define POSIX_MADV_DONTNEED __WASI_ADVICE_DONTNEED
#define POSIX_MADV_NORMAL __WASI_ADVICE_NORMAL
#define POSIX_MADV_RANDOM __WASI_ADVICE_RANDOM
#define POSIX_MADV_SEQUENTIAL __WASI_ADVICE_SEQUENTIAL
#define POSIX_MADV_WILLNEED __WASI_ADVICE_WILLNEED

#define MS_ASYNC __WASI_MS_ASYNC
#define MS_INVALIDATE __WASI_MS_INVALIDATE
#define MS_SYNC __WASI_MS_SYNC

#endif
