#ifndef __wasilibc___header_sys_socket_h
#define __wasilibc___header_sys_socket_h

#include <__struct_msghdr.h>
#include <__struct_sockaddr.h>
#include <__struct_sockaddr_storage.h>

#include <wasi/api.h>

#define SHUT_RD __WASI_SDFLAGS_RD
#define SHUT_WR __WASI_SDFLAGS_WR
#define SHUT_RDWR (SHUT_RD | SHUT_WR)

#define MSG_PEEK __WASI_RIFLAGS_RECV_PEEK
#define MSG_WAITALL __WASI_RIFLAGS_RECV_WAITALL
#define MSG_TRUNC __WASI_RIFLAGS_RECV_DATA_TRUNCATED

#define SOCK_DGRAM __WASI_FILETYPE_SOCKET_DGRAM
#define SOCK_STREAM __WASI_FILETYPE_SOCKET_STREAM

#define SOCK_NONBLOCK (0x00004000)
#define SOCK_CLOEXEC (0x00002000)

#define SOL_SOCKET 0x7fffffff

#define SO_ACCEPTCONN __WASI_SOCK_OPTION_LISTENING
#define SO_BROADCAST __WASI_SOCK_OPTION_BROADCAST
#define SO_DONTROUTE __WASI_SOCK_OPTION_DONT_ROUTE
#define SO_NODELAY __WASI_SOCK_OPTION_NO_DELAY
#define SO_ERROR __WASI_SOCK_OPTION_LAST_ERROR
#define SO_KEEPALIVE __WASI_SOCK_OPTION_KEEP_ALIVE
#define SO_LINGER __WASI_SOCK_OPTION_LINGER
#define SO_OOBINLINE __WASI_SOCK_OPTION_OOB_INLINE
#define SO_ONLYV6 __WASI_SOCK_OPTION_ONLY_V6
#define SO_RCVBUF __WASI_SOCK_OPTION_RECV_BUF_SIZE
#define SO_RCVLOWAT __WASI_SOCK_OPTION_RECV_LOWAT
#define SO_RCVTIMEO __WASI_SOCK_OPTION_RECV_TIMEOUT
#define SO_REUSEPORT __WASI_SOCK_OPTION_REUSE_PORT
#define SO_REUSEADDR __WASI_SOCK_OPTION_REUSE_ADDR
#define SO_SNDBUF __WASI_SOCK_OPTION_SEND_BUF_SIZE
#define SO_SNDLOWAT __WASI_SOCK_OPTION_SEND_LOWAT
#define SO_SNDTIMEO __WASI_SOCK_OPTION_SEND_TIMEOUT
#define SO_MCASTLOOPV4 __WASI_SOCK_OPTION_MULTICAST_LOOP_V4
#define SO_MCASTLOOPV6 __WASI_SOCK_OPTION_MULTICAST_LOOP_V6
#define SO_CONNTIMEO __WASI_SOCK_OPTION_CONNECT_TIMEOUT
#define SO_ACCPTIMEO __WASI_SOCK_OPTION_ACCEPT_TIMEOUT
#define SO_TYPE __WASI_SOCK_OPTION_TYPE

#define AF_UNSPEC __WASI_ADDRESS_FAMILY_UNSPEC
#define AF_INET __WASI_ADDRESS_FAMILY_INET4
#define AF_INET6 __WASI_ADDRESS_FAMILY_INET6
#define AF_UNIX __WASI_ADDRESS_FAMILY_UNIX

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif
