#ifndef __wasilibc___wasilibc_fcntl_h
#define __wasilibc___wasilibc_fcntl_h

#include <wasi.h>

#define O_APPEND WASI_FDFLAG_APPEND
#define O_DSYNC WASI_FDFLAG_DSYNC
#define O_NONBLOCK WASI_FDFLAG_NONBLOCK
#define O_RSYNC WASI_FDFLAG_RSYNC
#define O_SYNC WASI_FDFLAG_SYNC
#define O_CREAT (WASI_O_CREAT << 12)
#define O_DIRECTORY (WASI_O_DIRECTORY << 12)
#define O_EXCL (WASI_O_EXCL << 12)
#define O_TRUNC (WASI_O_TRUNC << 12)

#define O_NOFOLLOW 0x1000000
#define O_EXEC 0x2000000
#define O_RDONLY 0x4000000
#define O_SEARCH 0x8000000
#define O_WRONLY 0x10000000

#define O_CLOEXEC 0
#define O_NOCTTY 0

#define O_RDWR (O_RDONLY | O_WRONLY)
#define O_ACCMODE (O_EXEC | O_RDWR | O_SEARCH)

#define POSIX_FADV_DONTNEED WASI_ADVICE_DONTNEED
#define POSIX_FADV_NOREUSE WASI_ADVICE_NOREUSE
#define POSIX_FADV_NORMAL WASI_ADVICE_NORMAL
#define POSIX_FADV_RANDOM WASI_ADVICE_RANDOM
#define POSIX_FADV_SEQUENTIAL WASI_ADVICE_SEQUENTIAL
#define POSIX_FADV_WILLNEED WASI_ADVICE_WILLNEED

#define F_GETFD 1
#define F_SETFD 2
#define F_GETFL 3
#define F_SETFL 4

#define FD_CLOEXEC 1

#define AT_EACCESS 0x0
#define AT_SYMLINK_NOFOLLOW 0x1
#define AT_SYMLINK_FOLLOW 0x2
#define AT_REMOVEDIR 0x4

#endif
