#!/bin/bash

# -DCMAKE_MODULE_PATH=${CMAKE_CURRENT_SOURCE_DIR}/cmake \

mkdir -p build/compiler-rt
cd build/compiler-rt
cmake \
    -DCMAKE_SYSTEM_NAME=WASI \
    -DCMAKE_SYSTEM_VERSION=1 \
    -DCMAKE_SYSTEM_PROCESSOR=wasm32 \
    -DCMAKE_BUILD_TYPE=RelWithDebugInfo \
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
    -DCMAKE_C_COMPILER_WORKS=ON \
    -DCMAKE_CXX_COMPILER_WORKS=ON \
    -DCMAKE_C_LINKER_DEPFILE_SUPPORTED=OFF \
    -DCMAKE_CXX_LINKER_DEPFILE_SUPPORTED=OFF \
    -DCOMPILER_RT_BAREMETAL_BUILD=ON \
    -DCOMPILER_RT_BUILD_XRAY=OFF \
    -DCOMPILER_RT_INCLUDE_TESTS=OFF \
    -DCOMPILER_RT_HAS_FPIC_FLAG=ON \
    -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
    -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
    -DCOMPILER_RT_BUILD_XRAY=OFF \
    -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
    -DCOMPILER_RT_BUILD_PROFILE=OFF \
    -DCOMPILER_RT_BUILD_CTX_PROFILE=OFF \
    -DCOMPILER_RT_BUILD_MEMPROF=OFF \
    -DCOMPILER_RT_BUILD_ORC=OFF \
    -DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
    -DCOMPILER_RT_USE_LLVM_UNWINDER=OFF \
    -DSANITIZER_USE_STATIC_LLVM_UNWINDER=OFF \
    -DCOMPILER_RT_ENABLE_STATIC_UNWINDER=OFF \
    -DHAVE_UNWIND_H=OFF \
    -DCOMPILER_RT_HAS_FUNWIND_TABLES_FLAG=OFF \
    -DCMAKE_C_COMPILER_TARGET=wasm32-wasi \
    -DCOMPILER_RT_OS_DIR=wasi \
    -DCMAKE_TOOLCHAIN_FILE=$(pwd)/../../tools/clang-wasix.cmake_toolchain \
    -DCMAKE_SYSROOT=$(pwd)/../../sysroot \
    -DCMAKE_INSTALL_PREFIX=$(pwd)/../../sysroot \
    -DCXX_SUPPORTS_CXX23=ON \
    -DLLVM_COMPILER_CHECKED=ON \
    -DUNIX:BOOL=ON \
    ../../tools/llvm-project/compiler-rt
cmake --build . --target install --parallel 16
cd ../..

