# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ANT.AMAZON.COM/mkolny/wasm-threads/wasi-libc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ANT.AMAZON.COM/mkolny/wasm-threads/wasi-libc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ANT.AMAZON.COM/mkolny/wasm-threads/wasi-libc/CMakeFiles /home/ANT.AMAZON.COM/mkolny/wasm-threads/wasi-libc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ANT.AMAZON.COM/mkolny/wasm-threads/wasi-libc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/ANT.AMAZON.COM/mkolny/wasm-threads/wasi-libc/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sysroot-headers

# Build rule for target.
sysroot-headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sysroot-headers
.PHONY : sysroot-headers

# fast build rule for target.
sysroot-headers/fast:
	$(MAKE) -f cmake/CMakeFiles/sysroot-headers.dir/build.make cmake/CMakeFiles/sysroot-headers.dir/build
.PHONY : sysroot-headers/fast

#=============================================================================
# Target rules for targets named wasi-emulated-signal

# Build rule for target.
wasi-emulated-signal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasi-emulated-signal
.PHONY : wasi-emulated-signal

# fast build rule for target.
wasi-emulated-signal/fast:
	$(MAKE) -f cmake/CMakeFiles/wasi-emulated-signal.dir/build.make cmake/CMakeFiles/wasi-emulated-signal.dir/build
.PHONY : wasi-emulated-signal/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f cmake/CMakeFiles/util.dir/build.make cmake/CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named predefined-macros

# Build rule for target.
predefined-macros: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predefined-macros
.PHONY : predefined-macros

# fast build rule for target.
predefined-macros/fast:
	$(MAKE) -f cmake/CMakeFiles/predefined-macros.dir/build.make cmake/CMakeFiles/predefined-macros.dir/build
.PHONY : predefined-macros/fast

#=============================================================================
# Target rules for targets named libc.imports

# Build rule for target.
libc.imports: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libc.imports
.PHONY : libc.imports

# fast build rule for target.
libc.imports/fast:
	$(MAKE) -f cmake/CMakeFiles/libc.imports.dir/build.make cmake/CMakeFiles/libc.imports.dir/build
.PHONY : libc.imports/fast

#=============================================================================
# Target rules for targets named pthread

# Build rule for target.
pthread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pthread
.PHONY : pthread

# fast build rule for target.
pthread/fast:
	$(MAKE) -f cmake/CMakeFiles/pthread.dir/build.make cmake/CMakeFiles/pthread.dir/build
.PHONY : pthread/fast

#=============================================================================
# Target rules for targets named c

# Build rule for target.
c : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c
.PHONY : c

# fast build rule for target.
c/fast:
	$(MAKE) -f cmake/CMakeFiles/c.dir/build.make cmake/CMakeFiles/c.dir/build
.PHONY : c/fast

#=============================================================================
# Target rules for targets named m

# Build rule for target.
m : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m
.PHONY : m

# fast build rule for target.
m/fast:
	$(MAKE) -f cmake/CMakeFiles/m.dir/build.make cmake/CMakeFiles/m.dir/build
.PHONY : m/fast

#=============================================================================
# Target rules for targets named rt

# Build rule for target.
rt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rt
.PHONY : rt

# fast build rule for target.
rt/fast:
	$(MAKE) -f cmake/CMakeFiles/rt.dir/build.make cmake/CMakeFiles/rt.dir/build
.PHONY : rt/fast

#=============================================================================
# Target rules for targets named crypt

# Build rule for target.
crypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypt
.PHONY : crypt

# fast build rule for target.
crypt/fast:
	$(MAKE) -f cmake/CMakeFiles/crypt.dir/build.make cmake/CMakeFiles/crypt.dir/build
.PHONY : crypt/fast

#=============================================================================
# Target rules for targets named resolve

# Build rule for target.
resolve: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resolve
.PHONY : resolve

# fast build rule for target.
resolve/fast:
	$(MAKE) -f cmake/CMakeFiles/resolve.dir/build.make cmake/CMakeFiles/resolve.dir/build
.PHONY : resolve/fast

#=============================================================================
# Target rules for targets named dl

# Build rule for target.
dl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dl
.PHONY : dl

# fast build rule for target.
dl/fast:
	$(MAKE) -f cmake/CMakeFiles/dl.dir/build.make cmake/CMakeFiles/dl.dir/build
.PHONY : dl/fast

#=============================================================================
# Target rules for targets named xnet

# Build rule for target.
xnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xnet
.PHONY : xnet

# fast build rule for target.
xnet/fast:
	$(MAKE) -f cmake/CMakeFiles/xnet.dir/build.make cmake/CMakeFiles/xnet.dir/build
.PHONY : xnet/fast

#=============================================================================
# Target rules for targets named libc-bottom-half

# Build rule for target.
libc-bottom-half: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libc-bottom-half
.PHONY : libc-bottom-half

# fast build rule for target.
libc-bottom-half/fast:
	$(MAKE) -f cmake/libc-bottom-half/CMakeFiles/libc-bottom-half.dir/build.make cmake/libc-bottom-half/CMakeFiles/libc-bottom-half.dir/build
.PHONY : libc-bottom-half/fast

#=============================================================================
# Target rules for targets named wasi-emulated-process-clocks

# Build rule for target.
wasi-emulated-process-clocks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasi-emulated-process-clocks
.PHONY : wasi-emulated-process-clocks

# fast build rule for target.
wasi-emulated-process-clocks/fast:
	$(MAKE) -f cmake/libc-bottom-half/clocks/CMakeFiles/wasi-emulated-process-clocks.dir/build.make cmake/libc-bottom-half/clocks/CMakeFiles/wasi-emulated-process-clocks.dir/build
.PHONY : wasi-emulated-process-clocks/fast

#=============================================================================
# Target rules for targets named wasi-emulated-getpid

# Build rule for target.
wasi-emulated-getpid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasi-emulated-getpid
.PHONY : wasi-emulated-getpid

# fast build rule for target.
wasi-emulated-getpid/fast:
	$(MAKE) -f cmake/libc-bottom-half/getpid/CMakeFiles/wasi-emulated-getpid.dir/build.make cmake/libc-bottom-half/getpid/CMakeFiles/wasi-emulated-getpid.dir/build
.PHONY : wasi-emulated-getpid/fast

#=============================================================================
# Target rules for targets named wasi-emulated-mman

# Build rule for target.
wasi-emulated-mman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasi-emulated-mman
.PHONY : wasi-emulated-mman

# fast build rule for target.
wasi-emulated-mman/fast:
	$(MAKE) -f cmake/libc-bottom-half/mman/CMakeFiles/wasi-emulated-mman.dir/build.make cmake/libc-bottom-half/mman/CMakeFiles/wasi-emulated-mman.dir/build
.PHONY : wasi-emulated-mman/fast

#=============================================================================
# Target rules for targets named wasi-emulated-signal-objs

# Build rule for target.
wasi-emulated-signal-objs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasi-emulated-signal-objs
.PHONY : wasi-emulated-signal-objs

# fast build rule for target.
wasi-emulated-signal-objs/fast:
	$(MAKE) -f cmake/libc-bottom-half/signal/CMakeFiles/wasi-emulated-signal-objs.dir/build.make cmake/libc-bottom-half/signal/CMakeFiles/wasi-emulated-signal-objs.dir/build
.PHONY : wasi-emulated-signal-objs/fast

#=============================================================================
# Target rules for targets named crt1.o

# Build rule for target.
crt1.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crt1.o
.PHONY : crt1.o

# fast build rule for target.
crt1.o/fast:
	$(MAKE) -f cmake/libc-bottom-half/crt1/CMakeFiles/crt1.o.dir/build.make cmake/libc-bottom-half/crt1/CMakeFiles/crt1.o.dir/build
.PHONY : crt1.o/fast

#=============================================================================
# Target rules for targets named crt1

# Build rule for target.
crt1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crt1
.PHONY : crt1

# fast build rule for target.
crt1/fast:
	$(MAKE) -f cmake/libc-bottom-half/crt1/CMakeFiles/crt1.dir/build.make cmake/libc-bottom-half/crt1/CMakeFiles/crt1.dir/build
.PHONY : crt1/fast

#=============================================================================
# Target rules for targets named crt1-reactor.o

# Build rule for target.
crt1-reactor.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crt1-reactor.o
.PHONY : crt1-reactor.o

# fast build rule for target.
crt1-reactor.o/fast:
	$(MAKE) -f cmake/libc-bottom-half/crt1/CMakeFiles/crt1-reactor.o.dir/build.make cmake/libc-bottom-half/crt1/CMakeFiles/crt1-reactor.o.dir/build
.PHONY : crt1-reactor.o/fast

#=============================================================================
# Target rules for targets named crt1-reactor

# Build rule for target.
crt1-reactor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crt1-reactor
.PHONY : crt1-reactor

# fast build rule for target.
crt1-reactor/fast:
	$(MAKE) -f cmake/libc-bottom-half/crt1/CMakeFiles/crt1-reactor.dir/build.make cmake/libc-bottom-half/crt1/CMakeFiles/crt1-reactor.dir/build
.PHONY : crt1-reactor/fast

#=============================================================================
# Target rules for targets named crt1-command.o

# Build rule for target.
crt1-command.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crt1-command.o
.PHONY : crt1-command.o

# fast build rule for target.
crt1-command.o/fast:
	$(MAKE) -f cmake/libc-bottom-half/crt1/CMakeFiles/crt1-command.o.dir/build.make cmake/libc-bottom-half/crt1/CMakeFiles/crt1-command.o.dir/build
.PHONY : crt1-command.o/fast

#=============================================================================
# Target rules for targets named crt1-command

# Build rule for target.
crt1-command: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crt1-command
.PHONY : crt1-command

# fast build rule for target.
crt1-command/fast:
	$(MAKE) -f cmake/libc-bottom-half/crt1/CMakeFiles/crt1-command.dir/build.make cmake/libc-bottom-half/crt1/CMakeFiles/crt1-command.dir/build
.PHONY : crt1-command/fast

#=============================================================================
# Target rules for targets named libc-top-half

# Build rule for target.
libc-top-half: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libc-top-half
.PHONY : libc-top-half

# fast build rule for target.
libc-top-half/fast:
	$(MAKE) -f cmake/libc-top-half/CMakeFiles/libc-top-half.dir/build.make cmake/libc-top-half/CMakeFiles/libc-top-half.dir/build
.PHONY : libc-top-half/fast

#=============================================================================
# Target rules for targets named wasi-emulated-signal-musl-objs

# Build rule for target.
wasi-emulated-signal-musl-objs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasi-emulated-signal-musl-objs
.PHONY : wasi-emulated-signal-musl-objs

# fast build rule for target.
wasi-emulated-signal-musl-objs/fast:
	$(MAKE) -f cmake/libc-top-half/musl/CMakeFiles/wasi-emulated-signal-musl-objs.dir/build.make cmake/libc-top-half/musl/CMakeFiles/wasi-emulated-signal-musl-objs.dir/build
.PHONY : wasi-emulated-signal-musl-objs/fast

#=============================================================================
# Target rules for targets named c-printscan-long-double

# Build rule for target.
c-printscan-long-double: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c-printscan-long-double
.PHONY : c-printscan-long-double

# fast build rule for target.
c-printscan-long-double/fast:
	$(MAKE) -f cmake/libc-top-half/musl/CMakeFiles/c-printscan-long-double.dir/build.make cmake/libc-top-half/musl/CMakeFiles/c-printscan-long-double.dir/build
.PHONY : c-printscan-long-double/fast

#=============================================================================
# Target rules for targets named c-printscan-no-floating-point

# Build rule for target.
c-printscan-no-floating-point: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c-printscan-no-floating-point
.PHONY : c-printscan-no-floating-point

# fast build rule for target.
c-printscan-no-floating-point/fast:
	$(MAKE) -f cmake/libc-top-half/musl/CMakeFiles/c-printscan-no-floating-point.dir/build.make cmake/libc-top-half/musl/CMakeFiles/c-printscan-no-floating-point.dir/build
.PHONY : c-printscan-no-floating-point/fast

#=============================================================================
# Target rules for targets named dlmalloc

# Build rule for target.
dlmalloc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dlmalloc
.PHONY : dlmalloc

# fast build rule for target.
dlmalloc/fast:
	$(MAKE) -f cmake/dlmalloc/CMakeFiles/dlmalloc.dir/build.make cmake/dlmalloc/CMakeFiles/dlmalloc.dir/build
.PHONY : dlmalloc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... sysroot-headers"
	@echo "... wasi-emulated-signal"
	@echo "... util"
	@echo "... predefined-macros"
	@echo "... libc.imports"
	@echo "... pthread"
	@echo "... c"
	@echo "... m"
	@echo "... rt"
	@echo "... crypt"
	@echo "... resolve"
	@echo "... dl"
	@echo "... xnet"
	@echo "... libc-bottom-half"
	@echo "... wasi-emulated-process-clocks"
	@echo "... wasi-emulated-getpid"
	@echo "... wasi-emulated-mman"
	@echo "... wasi-emulated-signal-objs"
	@echo "... crt1.o"
	@echo "... crt1"
	@echo "... crt1-reactor.o"
	@echo "... crt1-reactor"
	@echo "... crt1-command.o"
	@echo "... crt1-command"
	@echo "... libc-top-half"
	@echo "... wasi-emulated-signal-musl-objs"
	@echo "... c-printscan-long-double"
	@echo "... c-printscan-no-floating-point"
	@echo "... dlmalloc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/ANT.AMAZON.COM/mkolny/wasm-threads/wasi-libc/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

