// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
#ifndef __BINDINGS_WASIP2_H
#define __BINDINGS_WASIP2_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct wasip2_string_t {
  uint8_t*ptr;
  size_t len;
} wasip2_string_t;

typedef struct {
  wasip2_string_t f0;
  wasip2_string_t f1;
} wasip2_tuple2_string_string_t;

typedef struct {
  wasip2_tuple2_string_string_t *ptr;
  size_t len;
} wasip2_list_tuple2_string_string_t;

typedef struct {
  wasip2_string_t *ptr;
  size_t len;
} wasip2_list_string_t;

typedef struct {
  bool is_some;
  wasip2_string_t val;
} wasip2_option_string_t;

typedef struct {
  bool is_err;
} exit_result_void_void_t;

typedef struct io_error_own_error_t {
  int32_t __handle;
} io_error_own_error_t;

typedef struct io_error_borrow_error_t {
  int32_t __handle;
} io_error_borrow_error_t;

typedef struct poll_own_pollable_t {
  int32_t __handle;
} poll_own_pollable_t;

typedef struct poll_borrow_pollable_t {
  int32_t __handle;
} poll_borrow_pollable_t;

typedef struct {
  poll_borrow_pollable_t *ptr;
  size_t len;
} poll_list_borrow_pollable_t;

typedef struct {
  uint32_t *ptr;
  size_t len;
} wasip2_list_u32_t;

typedef io_error_own_error_t streams_own_error_t;

typedef struct streams_stream_error_t {
  uint8_t tag;
  union {
    streams_own_error_t     last_operation_failed;
  } val;
} streams_stream_error_t;

#define STREAMS_STREAM_ERROR_LAST_OPERATION_FAILED 0
#define STREAMS_STREAM_ERROR_CLOSED 1

typedef struct streams_own_input_stream_t {
  int32_t __handle;
} streams_own_input_stream_t;

typedef struct streams_borrow_input_stream_t {
  int32_t __handle;
} streams_borrow_input_stream_t;

typedef struct streams_own_output_stream_t {
  int32_t __handle;
} streams_own_output_stream_t;

typedef struct streams_borrow_output_stream_t {
  int32_t __handle;
} streams_borrow_output_stream_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} wasip2_list_u8_t;

typedef struct {
  bool is_err;
  union {
    wasip2_list_u8_t ok;
    streams_stream_error_t err;
  } val;
} streams_result_list_u8_stream_error_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    streams_stream_error_t err;
  } val;
} streams_result_u64_stream_error_t;

typedef poll_own_pollable_t streams_own_pollable_t;

typedef struct {
  bool is_err;
  union {
    streams_stream_error_t err;
  } val;
} streams_result_void_stream_error_t;

typedef streams_own_input_stream_t stdin_own_input_stream_t;

typedef streams_own_output_stream_t stdout_own_output_stream_t;

typedef streams_own_output_stream_t stderr_own_output_stream_t;

typedef struct terminal_input_own_terminal_input_t {
  int32_t __handle;
} terminal_input_own_terminal_input_t;

typedef struct terminal_input_borrow_terminal_input_t {
  int32_t __handle;
} terminal_input_borrow_terminal_input_t;

typedef struct terminal_output_own_terminal_output_t {
  int32_t __handle;
} terminal_output_own_terminal_output_t;

typedef struct terminal_output_borrow_terminal_output_t {
  int32_t __handle;
} terminal_output_borrow_terminal_output_t;

typedef terminal_input_own_terminal_input_t terminal_stdin_own_terminal_input_t;

typedef struct {
  bool is_some;
  terminal_stdin_own_terminal_input_t val;
} terminal_stdin_option_own_terminal_input_t;

typedef terminal_output_own_terminal_output_t terminal_stdout_own_terminal_output_t;

typedef struct {
  bool is_some;
  terminal_stdout_own_terminal_output_t val;
} terminal_stdout_option_own_terminal_output_t;

typedef terminal_output_own_terminal_output_t terminal_stderr_own_terminal_output_t;

typedef struct {
  bool is_some;
  terminal_stderr_own_terminal_output_t val;
} terminal_stderr_option_own_terminal_output_t;

typedef uint64_t monotonic_clock_instant_t;

typedef uint64_t monotonic_clock_duration_t;

typedef poll_own_pollable_t monotonic_clock_own_pollable_t;

typedef struct wall_clock_datetime_t {
  uint64_t   seconds;
  uint32_t   nanoseconds;
} wall_clock_datetime_t;

typedef wall_clock_datetime_t filesystem_datetime_t;

typedef uint64_t filesystem_filesize_t;

typedef uint8_t filesystem_descriptor_type_t;

#define FILESYSTEM_DESCRIPTOR_TYPE_UNKNOWN 0
#define FILESYSTEM_DESCRIPTOR_TYPE_BLOCK_DEVICE 1
#define FILESYSTEM_DESCRIPTOR_TYPE_CHARACTER_DEVICE 2
#define FILESYSTEM_DESCRIPTOR_TYPE_DIRECTORY 3
#define FILESYSTEM_DESCRIPTOR_TYPE_FIFO 4
#define FILESYSTEM_DESCRIPTOR_TYPE_SYMBOLIC_LINK 5
#define FILESYSTEM_DESCRIPTOR_TYPE_REGULAR_FILE 6
#define FILESYSTEM_DESCRIPTOR_TYPE_SOCKET 7

typedef uint8_t filesystem_descriptor_flags_t;

#define FILESYSTEM_DESCRIPTOR_FLAGS_READ (1 << 0)
#define FILESYSTEM_DESCRIPTOR_FLAGS_WRITE (1 << 1)
#define FILESYSTEM_DESCRIPTOR_FLAGS_FILE_INTEGRITY_SYNC (1 << 2)
#define FILESYSTEM_DESCRIPTOR_FLAGS_DATA_INTEGRITY_SYNC (1 << 3)
#define FILESYSTEM_DESCRIPTOR_FLAGS_REQUESTED_WRITE_SYNC (1 << 4)
#define FILESYSTEM_DESCRIPTOR_FLAGS_MUTATE_DIRECTORY (1 << 5)

typedef uint8_t filesystem_path_flags_t;

#define FILESYSTEM_PATH_FLAGS_SYMLINK_FOLLOW (1 << 0)

typedef uint8_t filesystem_open_flags_t;

#define FILESYSTEM_OPEN_FLAGS_CREATE (1 << 0)
#define FILESYSTEM_OPEN_FLAGS_DIRECTORY (1 << 1)
#define FILESYSTEM_OPEN_FLAGS_EXCLUSIVE (1 << 2)
#define FILESYSTEM_OPEN_FLAGS_TRUNCATE (1 << 3)

typedef uint64_t filesystem_link_count_t;

typedef struct {
  bool is_some;
  filesystem_datetime_t val;
} filesystem_option_datetime_t;

typedef struct filesystem_descriptor_stat_t {
  filesystem_descriptor_type_t   type;
  filesystem_link_count_t   link_count;
  filesystem_filesize_t   size;
  filesystem_option_datetime_t   data_access_timestamp;
  filesystem_option_datetime_t   data_modification_timestamp;
  filesystem_option_datetime_t   status_change_timestamp;
} filesystem_descriptor_stat_t;

typedef struct filesystem_new_timestamp_t {
  uint8_t tag;
  union {
    filesystem_datetime_t     timestamp;
  } val;
} filesystem_new_timestamp_t;

#define FILESYSTEM_NEW_TIMESTAMP_NO_CHANGE 0
#define FILESYSTEM_NEW_TIMESTAMP_NOW 1
#define FILESYSTEM_NEW_TIMESTAMP_TIMESTAMP 2

typedef struct filesystem_directory_entry_t {
  filesystem_descriptor_type_t   type;
  wasip2_string_t   name;
} filesystem_directory_entry_t;

typedef uint8_t filesystem_error_code_t;

#define FILESYSTEM_ERROR_CODE_ACCESS 0
#define FILESYSTEM_ERROR_CODE_WOULD_BLOCK 1
#define FILESYSTEM_ERROR_CODE_ALREADY 2
#define FILESYSTEM_ERROR_CODE_BAD_DESCRIPTOR 3
#define FILESYSTEM_ERROR_CODE_BUSY 4
#define FILESYSTEM_ERROR_CODE_DEADLOCK 5
#define FILESYSTEM_ERROR_CODE_QUOTA 6
#define FILESYSTEM_ERROR_CODE_EXIST 7
#define FILESYSTEM_ERROR_CODE_FILE_TOO_LARGE 8
#define FILESYSTEM_ERROR_CODE_ILLEGAL_BYTE_SEQUENCE 9
#define FILESYSTEM_ERROR_CODE_IN_PROGRESS 10
#define FILESYSTEM_ERROR_CODE_INTERRUPTED 11
#define FILESYSTEM_ERROR_CODE_INVALID 12
#define FILESYSTEM_ERROR_CODE_IO 13
#define FILESYSTEM_ERROR_CODE_IS_DIRECTORY 14
#define FILESYSTEM_ERROR_CODE_LOOP 15
#define FILESYSTEM_ERROR_CODE_TOO_MANY_LINKS 16
#define FILESYSTEM_ERROR_CODE_MESSAGE_SIZE 17
#define FILESYSTEM_ERROR_CODE_NAME_TOO_LONG 18
#define FILESYSTEM_ERROR_CODE_NO_DEVICE 19
#define FILESYSTEM_ERROR_CODE_NO_ENTRY 20
#define FILESYSTEM_ERROR_CODE_NO_LOCK 21
#define FILESYSTEM_ERROR_CODE_INSUFFICIENT_MEMORY 22
#define FILESYSTEM_ERROR_CODE_INSUFFICIENT_SPACE 23
#define FILESYSTEM_ERROR_CODE_NOT_DIRECTORY 24
#define FILESYSTEM_ERROR_CODE_NOT_EMPTY 25
#define FILESYSTEM_ERROR_CODE_NOT_RECOVERABLE 26
#define FILESYSTEM_ERROR_CODE_UNSUPPORTED 27
#define FILESYSTEM_ERROR_CODE_NO_TTY 28
#define FILESYSTEM_ERROR_CODE_NO_SUCH_DEVICE 29
#define FILESYSTEM_ERROR_CODE_OVERFLOW 30
#define FILESYSTEM_ERROR_CODE_NOT_PERMITTED 31
#define FILESYSTEM_ERROR_CODE_PIPE 32
#define FILESYSTEM_ERROR_CODE_READ_ONLY 33
#define FILESYSTEM_ERROR_CODE_INVALID_SEEK 34
#define FILESYSTEM_ERROR_CODE_TEXT_FILE_BUSY 35
#define FILESYSTEM_ERROR_CODE_CROSS_DEVICE 36

typedef uint8_t filesystem_advice_t;

#define FILESYSTEM_ADVICE_NORMAL 0
#define FILESYSTEM_ADVICE_SEQUENTIAL 1
#define FILESYSTEM_ADVICE_RANDOM 2
#define FILESYSTEM_ADVICE_WILL_NEED 3
#define FILESYSTEM_ADVICE_DONT_NEED 4
#define FILESYSTEM_ADVICE_NO_REUSE 5

typedef struct filesystem_metadata_hash_value_t {
  uint64_t   lower;
  uint64_t   upper;
} filesystem_metadata_hash_value_t;

typedef struct filesystem_own_descriptor_t {
  int32_t __handle;
} filesystem_own_descriptor_t;

typedef struct filesystem_borrow_descriptor_t {
  int32_t __handle;
} filesystem_borrow_descriptor_t;

typedef struct filesystem_own_directory_entry_stream_t {
  int32_t __handle;
} filesystem_own_directory_entry_stream_t;

typedef struct filesystem_borrow_directory_entry_stream_t {
  int32_t __handle;
} filesystem_borrow_directory_entry_stream_t;

typedef streams_own_input_stream_t filesystem_own_input_stream_t;

typedef struct {
  bool is_err;
  union {
    filesystem_own_input_stream_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_own_input_stream_error_code_t;

typedef streams_own_output_stream_t filesystem_own_output_stream_t;

typedef struct {
  bool is_err;
  union {
    filesystem_own_output_stream_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_own_output_stream_error_code_t;

typedef struct {
  bool is_err;
  union {
    filesystem_error_code_t err;
  } val;
} filesystem_result_void_error_code_t;

typedef struct {
  bool is_err;
  union {
    filesystem_descriptor_flags_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_descriptor_flags_error_code_t;

typedef struct {
  bool is_err;
  union {
    filesystem_descriptor_type_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_descriptor_type_error_code_t;

typedef struct {
  wasip2_list_u8_t f0;
  bool f1;
} wasip2_tuple2_list_u8_bool_t;

typedef struct {
  bool is_err;
  union {
    wasip2_tuple2_list_u8_bool_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_tuple2_list_u8_bool_error_code_t;

typedef struct {
  bool is_err;
  union {
    filesystem_filesize_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_filesize_error_code_t;

typedef struct {
  bool is_err;
  union {
    filesystem_own_directory_entry_stream_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_own_directory_entry_stream_error_code_t;

typedef struct {
  bool is_err;
  union {
    filesystem_descriptor_stat_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_descriptor_stat_error_code_t;

typedef struct {
  bool is_err;
  union {
    filesystem_own_descriptor_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_own_descriptor_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasip2_string_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_string_error_code_t;

typedef struct {
  bool is_err;
  union {
    filesystem_metadata_hash_value_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_metadata_hash_value_error_code_t;

typedef struct {
  bool is_some;
  filesystem_directory_entry_t val;
} filesystem_option_directory_entry_t;

typedef struct {
  bool is_err;
  union {
    filesystem_option_directory_entry_t ok;
    filesystem_error_code_t err;
  } val;
} filesystem_result_option_directory_entry_error_code_t;

typedef io_error_borrow_error_t filesystem_borrow_error_t;

typedef struct {
  bool is_some;
  filesystem_error_code_t val;
} filesystem_option_error_code_t;

typedef filesystem_own_descriptor_t filesystem_preopens_own_descriptor_t;

typedef struct {
  filesystem_preopens_own_descriptor_t f0;
  wasip2_string_t f1;
} filesystem_preopens_tuple2_own_descriptor_string_t;

typedef struct {
  filesystem_preopens_tuple2_own_descriptor_string_t *ptr;
  size_t len;
} filesystem_preopens_list_tuple2_own_descriptor_string_t;

typedef struct network_own_network_t {
  int32_t __handle;
} network_own_network_t;

typedef struct network_borrow_network_t {
  int32_t __handle;
} network_borrow_network_t;

typedef uint8_t network_error_code_t;

#define NETWORK_ERROR_CODE_UNKNOWN 0
#define NETWORK_ERROR_CODE_ACCESS_DENIED 1
#define NETWORK_ERROR_CODE_NOT_SUPPORTED 2
#define NETWORK_ERROR_CODE_INVALID_ARGUMENT 3
#define NETWORK_ERROR_CODE_OUT_OF_MEMORY 4
#define NETWORK_ERROR_CODE_TIMEOUT 5
#define NETWORK_ERROR_CODE_CONCURRENCY_CONFLICT 6
#define NETWORK_ERROR_CODE_NOT_IN_PROGRESS 7
#define NETWORK_ERROR_CODE_WOULD_BLOCK 8
#define NETWORK_ERROR_CODE_INVALID_STATE 9
#define NETWORK_ERROR_CODE_NEW_SOCKET_LIMIT 10
#define NETWORK_ERROR_CODE_ADDRESS_NOT_BINDABLE 11
#define NETWORK_ERROR_CODE_ADDRESS_IN_USE 12
#define NETWORK_ERROR_CODE_REMOTE_UNREACHABLE 13
#define NETWORK_ERROR_CODE_CONNECTION_REFUSED 14
#define NETWORK_ERROR_CODE_CONNECTION_RESET 15
#define NETWORK_ERROR_CODE_CONNECTION_ABORTED 16
#define NETWORK_ERROR_CODE_DATAGRAM_TOO_LARGE 17
#define NETWORK_ERROR_CODE_NAME_UNRESOLVABLE 18
#define NETWORK_ERROR_CODE_TEMPORARY_RESOLVER_FAILURE 19
#define NETWORK_ERROR_CODE_PERMANENT_RESOLVER_FAILURE 20

typedef uint8_t network_ip_address_family_t;

#define NETWORK_IP_ADDRESS_FAMILY_IPV4 0
#define NETWORK_IP_ADDRESS_FAMILY_IPV6 1

typedef struct network_ipv4_address_t {
  uint8_t   f0;
  uint8_t   f1;
  uint8_t   f2;
  uint8_t   f3;
} network_ipv4_address_t;

typedef struct network_ipv6_address_t {
  uint16_t   f0;
  uint16_t   f1;
  uint16_t   f2;
  uint16_t   f3;
  uint16_t   f4;
  uint16_t   f5;
  uint16_t   f6;
  uint16_t   f7;
} network_ipv6_address_t;

typedef struct network_ip_address_t {
  uint8_t tag;
  union {
    network_ipv4_address_t     ipv4;
    network_ipv6_address_t     ipv6;
  } val;
} network_ip_address_t;

#define NETWORK_IP_ADDRESS_IPV4 0
#define NETWORK_IP_ADDRESS_IPV6 1

typedef struct network_ipv4_socket_address_t {
  uint16_t   port;
  network_ipv4_address_t   address;
} network_ipv4_socket_address_t;

typedef struct network_ipv6_socket_address_t {
  uint16_t   port;
  uint32_t   flow_info;
  network_ipv6_address_t   address;
  uint32_t   scope_id;
} network_ipv6_socket_address_t;

typedef struct network_ip_socket_address_t {
  uint8_t tag;
  union {
    network_ipv4_socket_address_t     ipv4;
    network_ipv6_socket_address_t     ipv6;
  } val;
} network_ip_socket_address_t;

#define NETWORK_IP_SOCKET_ADDRESS_IPV4 0
#define NETWORK_IP_SOCKET_ADDRESS_IPV6 1

typedef network_own_network_t instance_network_own_network_t;

typedef network_error_code_t udp_error_code_t;

typedef network_ip_socket_address_t udp_ip_socket_address_t;

typedef network_ip_address_family_t udp_ip_address_family_t;

typedef struct udp_incoming_datagram_t {
  wasip2_list_u8_t   data;
  udp_ip_socket_address_t   remote_address;
} udp_incoming_datagram_t;

typedef struct {
  bool is_some;
  udp_ip_socket_address_t val;
} udp_option_ip_socket_address_t;

typedef struct udp_outgoing_datagram_t {
  wasip2_list_u8_t   data;
  udp_option_ip_socket_address_t   remote_address;
} udp_outgoing_datagram_t;

typedef struct udp_own_udp_socket_t {
  int32_t __handle;
} udp_own_udp_socket_t;

typedef struct udp_borrow_udp_socket_t {
  int32_t __handle;
} udp_borrow_udp_socket_t;

typedef struct udp_own_incoming_datagram_stream_t {
  int32_t __handle;
} udp_own_incoming_datagram_stream_t;

typedef struct udp_borrow_incoming_datagram_stream_t {
  int32_t __handle;
} udp_borrow_incoming_datagram_stream_t;

typedef struct udp_own_outgoing_datagram_stream_t {
  int32_t __handle;
} udp_own_outgoing_datagram_stream_t;

typedef struct udp_borrow_outgoing_datagram_stream_t {
  int32_t __handle;
} udp_borrow_outgoing_datagram_stream_t;

typedef network_borrow_network_t udp_borrow_network_t;

typedef struct {
  bool is_err;
  union {
    udp_error_code_t err;
  } val;
} udp_result_void_error_code_t;

typedef struct {
  udp_own_incoming_datagram_stream_t f0;
  udp_own_outgoing_datagram_stream_t f1;
} udp_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_t;

typedef struct {
  bool is_err;
  union {
    udp_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_t ok;
    udp_error_code_t err;
  } val;
} udp_result_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_error_code_t;

typedef struct {
  bool is_err;
  union {
    udp_ip_socket_address_t ok;
    udp_error_code_t err;
  } val;
} udp_result_ip_socket_address_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint8_t ok;
    udp_error_code_t err;
  } val;
} udp_result_u8_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    udp_error_code_t err;
  } val;
} udp_result_u64_error_code_t;

typedef poll_own_pollable_t udp_own_pollable_t;

typedef struct {
  udp_incoming_datagram_t *ptr;
  size_t len;
} udp_list_incoming_datagram_t;

typedef struct {
  bool is_err;
  union {
    udp_list_incoming_datagram_t ok;
    udp_error_code_t err;
  } val;
} udp_result_list_incoming_datagram_error_code_t;

typedef struct {
  udp_outgoing_datagram_t *ptr;
  size_t len;
} udp_list_outgoing_datagram_t;

typedef network_error_code_t udp_create_socket_error_code_t;

typedef network_ip_address_family_t udp_create_socket_ip_address_family_t;

typedef udp_own_udp_socket_t udp_create_socket_own_udp_socket_t;

typedef struct {
  bool is_err;
  union {
    udp_create_socket_own_udp_socket_t ok;
    udp_create_socket_error_code_t err;
  } val;
} udp_create_socket_result_own_udp_socket_error_code_t;

typedef monotonic_clock_duration_t tcp_duration_t;

typedef network_error_code_t tcp_error_code_t;

typedef network_ip_socket_address_t tcp_ip_socket_address_t;

typedef network_ip_address_family_t tcp_ip_address_family_t;

typedef uint8_t tcp_shutdown_type_t;

#define TCP_SHUTDOWN_TYPE_RECEIVE 0
#define TCP_SHUTDOWN_TYPE_SEND 1
#define TCP_SHUTDOWN_TYPE_BOTH 2

typedef struct tcp_own_tcp_socket_t {
  int32_t __handle;
} tcp_own_tcp_socket_t;

typedef struct tcp_borrow_tcp_socket_t {
  int32_t __handle;
} tcp_borrow_tcp_socket_t;

typedef network_borrow_network_t tcp_borrow_network_t;

typedef struct {
  bool is_err;
  union {
    tcp_error_code_t err;
  } val;
} tcp_result_void_error_code_t;

typedef streams_own_input_stream_t tcp_own_input_stream_t;

typedef streams_own_output_stream_t tcp_own_output_stream_t;

typedef struct {
  tcp_own_input_stream_t f0;
  tcp_own_output_stream_t f1;
} tcp_tuple2_own_input_stream_own_output_stream_t;

typedef struct {
  bool is_err;
  union {
    tcp_tuple2_own_input_stream_own_output_stream_t ok;
    tcp_error_code_t err;
  } val;
} tcp_result_tuple2_own_input_stream_own_output_stream_error_code_t;

typedef struct {
  tcp_own_tcp_socket_t f0;
  tcp_own_input_stream_t f1;
  tcp_own_output_stream_t f2;
} tcp_tuple3_own_tcp_socket_own_input_stream_own_output_stream_t;

typedef struct {
  bool is_err;
  union {
    tcp_tuple3_own_tcp_socket_own_input_stream_own_output_stream_t ok;
    tcp_error_code_t err;
  } val;
} tcp_result_tuple3_own_tcp_socket_own_input_stream_own_output_stream_error_code_t;

typedef struct {
  bool is_err;
  union {
    tcp_ip_socket_address_t ok;
    tcp_error_code_t err;
  } val;
} tcp_result_ip_socket_address_error_code_t;

typedef struct {
  bool is_err;
  union {
    bool ok;
    tcp_error_code_t err;
  } val;
} tcp_result_bool_error_code_t;

typedef struct {
  bool is_err;
  union {
    tcp_duration_t ok;
    tcp_error_code_t err;
  } val;
} tcp_result_duration_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint32_t ok;
    tcp_error_code_t err;
  } val;
} tcp_result_u32_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint8_t ok;
    tcp_error_code_t err;
  } val;
} tcp_result_u8_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    tcp_error_code_t err;
  } val;
} tcp_result_u64_error_code_t;

typedef poll_own_pollable_t tcp_own_pollable_t;

typedef network_error_code_t tcp_create_socket_error_code_t;

typedef network_ip_address_family_t tcp_create_socket_ip_address_family_t;

typedef tcp_own_tcp_socket_t tcp_create_socket_own_tcp_socket_t;

typedef struct {
  bool is_err;
  union {
    tcp_create_socket_own_tcp_socket_t ok;
    tcp_create_socket_error_code_t err;
  } val;
} tcp_create_socket_result_own_tcp_socket_error_code_t;

typedef network_error_code_t ip_name_lookup_error_code_t;

typedef network_ip_address_t ip_name_lookup_ip_address_t;

typedef struct ip_name_lookup_own_resolve_address_stream_t {
  int32_t __handle;
} ip_name_lookup_own_resolve_address_stream_t;

typedef struct ip_name_lookup_borrow_resolve_address_stream_t {
  int32_t __handle;
} ip_name_lookup_borrow_resolve_address_stream_t;

typedef struct {
  bool is_some;
  ip_name_lookup_ip_address_t val;
} ip_name_lookup_option_ip_address_t;

typedef struct {
  bool is_err;
  union {
    ip_name_lookup_option_ip_address_t ok;
    ip_name_lookup_error_code_t err;
  } val;
} ip_name_lookup_result_option_ip_address_error_code_t;

typedef poll_own_pollable_t ip_name_lookup_own_pollable_t;

typedef network_borrow_network_t ip_name_lookup_borrow_network_t;

typedef struct {
  bool is_err;
  union {
    ip_name_lookup_own_resolve_address_stream_t ok;
    ip_name_lookup_error_code_t err;
  } val;
} ip_name_lookup_result_own_resolve_address_stream_error_code_t;

typedef struct {
  uint64_t f0;
  uint64_t f1;
} wasip2_tuple2_u64_u64_t;

// Imported Functions from `wasi:cli/environment@0.2.0`
// Get the POSIX-style environment variables.
// 
// Each environment variable is provided as a pair of string variable names
// and string value.
// 
// Morally, these are a value import, but until value imports are available
// in the component model, this import function should return the same
// values each time it is called.
extern void environment_get_environment(wasip2_list_tuple2_string_string_t *ret);
// Get the POSIX-style arguments to the program.
extern void environment_get_arguments(wasip2_list_string_t *ret);
// Return a path that programs should use as their initial current working
// directory, interpreting `.` as shorthand for this.
extern bool environment_initial_cwd(wasip2_string_t *ret);

// Imported Functions from `wasi:cli/exit@0.2.0`
// Exit the current instance and any linked instances.
_Noreturn extern void exit_exit(exit_result_void_void_t *status);

// Imported Functions from `wasi:io/error@0.2.0`
extern void io_error_method_error_to_debug_string(io_error_borrow_error_t self, wasip2_string_t *ret);

// Imported Functions from `wasi:io/poll@0.2.0`
extern bool poll_method_pollable_ready(poll_borrow_pollable_t self);
extern void poll_method_pollable_block(poll_borrow_pollable_t self);
extern void poll_poll(poll_list_borrow_pollable_t *in, wasip2_list_u32_t *ret);

// Imported Functions from `wasi:io/streams@0.2.0`
extern bool streams_method_input_stream_read(streams_borrow_input_stream_t self, uint64_t len, wasip2_list_u8_t *ret, streams_stream_error_t *err);
extern bool streams_method_input_stream_blocking_read(streams_borrow_input_stream_t self, uint64_t len, wasip2_list_u8_t *ret, streams_stream_error_t *err);
extern bool streams_method_input_stream_skip(streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, streams_stream_error_t *err);
extern bool streams_method_input_stream_blocking_skip(streams_borrow_input_stream_t self, uint64_t len, uint64_t *ret, streams_stream_error_t *err);
extern streams_own_pollable_t streams_method_input_stream_subscribe(streams_borrow_input_stream_t self);
extern bool streams_method_output_stream_check_write(streams_borrow_output_stream_t self, uint64_t *ret, streams_stream_error_t *err);
extern bool streams_method_output_stream_write(streams_borrow_output_stream_t self, wasip2_list_u8_t *contents, streams_stream_error_t *err);
extern bool streams_method_output_stream_blocking_write_and_flush(streams_borrow_output_stream_t self, wasip2_list_u8_t *contents, streams_stream_error_t *err);
extern bool streams_method_output_stream_flush(streams_borrow_output_stream_t self, streams_stream_error_t *err);
extern bool streams_method_output_stream_blocking_flush(streams_borrow_output_stream_t self, streams_stream_error_t *err);
extern streams_own_pollable_t streams_method_output_stream_subscribe(streams_borrow_output_stream_t self);
extern bool streams_method_output_stream_write_zeroes(streams_borrow_output_stream_t self, uint64_t len, streams_stream_error_t *err);
extern bool streams_method_output_stream_blocking_write_zeroes_and_flush(streams_borrow_output_stream_t self, uint64_t len, streams_stream_error_t *err);
extern bool streams_method_output_stream_splice(streams_borrow_output_stream_t self, streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, streams_stream_error_t *err);
extern bool streams_method_output_stream_blocking_splice(streams_borrow_output_stream_t self, streams_borrow_input_stream_t src, uint64_t len, uint64_t *ret, streams_stream_error_t *err);

// Imported Functions from `wasi:cli/stdin@0.2.0`
extern stdin_own_input_stream_t stdin_get_stdin(void);

// Imported Functions from `wasi:cli/stdout@0.2.0`
extern stdout_own_output_stream_t stdout_get_stdout(void);

// Imported Functions from `wasi:cli/stderr@0.2.0`
extern stderr_own_output_stream_t stderr_get_stderr(void);

// Imported Functions from `wasi:cli/terminal-stdin@0.2.0`
// If stdin is connected to a terminal, return a `terminal-input` handle
// allowing further interaction with it.
extern bool terminal_stdin_get_terminal_stdin(terminal_stdin_own_terminal_input_t *ret);

// Imported Functions from `wasi:cli/terminal-stdout@0.2.0`
// If stdout is connected to a terminal, return a `terminal-output` handle
// allowing further interaction with it.
extern bool terminal_stdout_get_terminal_stdout(terminal_stdout_own_terminal_output_t *ret);

// Imported Functions from `wasi:cli/terminal-stderr@0.2.0`
// If stderr is connected to a terminal, return a `terminal-output` handle
// allowing further interaction with it.
extern bool terminal_stderr_get_terminal_stderr(terminal_stderr_own_terminal_output_t *ret);

// Imported Functions from `wasi:clocks/monotonic-clock@0.2.0`
extern monotonic_clock_instant_t monotonic_clock_now(void);
extern monotonic_clock_duration_t monotonic_clock_resolution(void);
extern monotonic_clock_own_pollable_t monotonic_clock_subscribe_instant(monotonic_clock_instant_t when);
extern monotonic_clock_own_pollable_t monotonic_clock_subscribe_duration(monotonic_clock_duration_t when);

// Imported Functions from `wasi:clocks/wall-clock@0.2.0`
extern void wall_clock_now(wall_clock_datetime_t *ret);
extern void wall_clock_resolution(wall_clock_datetime_t *ret);

// Imported Functions from `wasi:filesystem/types@0.2.0`
extern bool filesystem_method_descriptor_read_via_stream(filesystem_borrow_descriptor_t self, filesystem_filesize_t offset, filesystem_own_input_stream_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_write_via_stream(filesystem_borrow_descriptor_t self, filesystem_filesize_t offset, filesystem_own_output_stream_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_append_via_stream(filesystem_borrow_descriptor_t self, filesystem_own_output_stream_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_advise(filesystem_borrow_descriptor_t self, filesystem_filesize_t offset, filesystem_filesize_t length, filesystem_advice_t advice, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_sync_data(filesystem_borrow_descriptor_t self, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_get_flags(filesystem_borrow_descriptor_t self, filesystem_descriptor_flags_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_get_type(filesystem_borrow_descriptor_t self, filesystem_descriptor_type_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_set_size(filesystem_borrow_descriptor_t self, filesystem_filesize_t size, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_set_times(filesystem_borrow_descriptor_t self, filesystem_new_timestamp_t *data_access_timestamp, filesystem_new_timestamp_t *data_modification_timestamp, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_read(filesystem_borrow_descriptor_t self, filesystem_filesize_t length, filesystem_filesize_t offset, wasip2_tuple2_list_u8_bool_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_write(filesystem_borrow_descriptor_t self, wasip2_list_u8_t *buffer, filesystem_filesize_t offset, filesystem_filesize_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_read_directory(filesystem_borrow_descriptor_t self, filesystem_own_directory_entry_stream_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_sync(filesystem_borrow_descriptor_t self, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_create_directory_at(filesystem_borrow_descriptor_t self, wasip2_string_t *path, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_stat(filesystem_borrow_descriptor_t self, filesystem_descriptor_stat_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_stat_at(filesystem_borrow_descriptor_t self, filesystem_path_flags_t path_flags, wasip2_string_t *path, filesystem_descriptor_stat_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_set_times_at(filesystem_borrow_descriptor_t self, filesystem_path_flags_t path_flags, wasip2_string_t *path, filesystem_new_timestamp_t *data_access_timestamp, filesystem_new_timestamp_t *data_modification_timestamp, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_link_at(filesystem_borrow_descriptor_t self, filesystem_path_flags_t old_path_flags, wasip2_string_t *old_path, filesystem_borrow_descriptor_t new_descriptor, wasip2_string_t *new_path, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_open_at(filesystem_borrow_descriptor_t self, filesystem_path_flags_t path_flags, wasip2_string_t *path, filesystem_open_flags_t open_flags, filesystem_descriptor_flags_t flags, filesystem_own_descriptor_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_readlink_at(filesystem_borrow_descriptor_t self, wasip2_string_t *path, wasip2_string_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_remove_directory_at(filesystem_borrow_descriptor_t self, wasip2_string_t *path, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_rename_at(filesystem_borrow_descriptor_t self, wasip2_string_t *old_path, filesystem_borrow_descriptor_t new_descriptor, wasip2_string_t *new_path, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_symlink_at(filesystem_borrow_descriptor_t self, wasip2_string_t *old_path, wasip2_string_t *new_path, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_unlink_file_at(filesystem_borrow_descriptor_t self, wasip2_string_t *path, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_is_same_object(filesystem_borrow_descriptor_t self, filesystem_borrow_descriptor_t other);
extern bool filesystem_method_descriptor_metadata_hash(filesystem_borrow_descriptor_t self, filesystem_metadata_hash_value_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_descriptor_metadata_hash_at(filesystem_borrow_descriptor_t self, filesystem_path_flags_t path_flags, wasip2_string_t *path, filesystem_metadata_hash_value_t *ret, filesystem_error_code_t *err);
extern bool filesystem_method_directory_entry_stream_read_directory_entry(filesystem_borrow_directory_entry_stream_t self, filesystem_option_directory_entry_t *ret, filesystem_error_code_t *err);
extern bool filesystem_filesystem_error_code(filesystem_borrow_error_t err_, filesystem_error_code_t *ret);

// Imported Functions from `wasi:filesystem/preopens@0.2.0`
extern void filesystem_preopens_get_directories(filesystem_preopens_list_tuple2_own_descriptor_string_t *ret);

// Imported Functions from `wasi:sockets/instance-network@0.2.0`
extern instance_network_own_network_t instance_network_instance_network(void);

// Imported Functions from `wasi:sockets/udp@0.2.0`
extern bool udp_method_udp_socket_start_bind(udp_borrow_udp_socket_t self, udp_borrow_network_t network, udp_ip_socket_address_t *local_address, udp_error_code_t *err);
extern bool udp_method_udp_socket_finish_bind(udp_borrow_udp_socket_t self, udp_error_code_t *err);
extern bool udp_method_udp_socket_stream(udp_borrow_udp_socket_t self, udp_ip_socket_address_t *maybe_remote_address, udp_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_t *ret, udp_error_code_t *err);
extern bool udp_method_udp_socket_local_address(udp_borrow_udp_socket_t self, udp_ip_socket_address_t *ret, udp_error_code_t *err);
extern bool udp_method_udp_socket_remote_address(udp_borrow_udp_socket_t self, udp_ip_socket_address_t *ret, udp_error_code_t *err);
extern udp_ip_address_family_t udp_method_udp_socket_address_family(udp_borrow_udp_socket_t self);
extern bool udp_method_udp_socket_unicast_hop_limit(udp_borrow_udp_socket_t self, uint8_t *ret, udp_error_code_t *err);
extern bool udp_method_udp_socket_set_unicast_hop_limit(udp_borrow_udp_socket_t self, uint8_t value, udp_error_code_t *err);
extern bool udp_method_udp_socket_receive_buffer_size(udp_borrow_udp_socket_t self, uint64_t *ret, udp_error_code_t *err);
extern bool udp_method_udp_socket_set_receive_buffer_size(udp_borrow_udp_socket_t self, uint64_t value, udp_error_code_t *err);
extern bool udp_method_udp_socket_send_buffer_size(udp_borrow_udp_socket_t self, uint64_t *ret, udp_error_code_t *err);
extern bool udp_method_udp_socket_set_send_buffer_size(udp_borrow_udp_socket_t self, uint64_t value, udp_error_code_t *err);
extern udp_own_pollable_t udp_method_udp_socket_subscribe(udp_borrow_udp_socket_t self);
extern bool udp_method_incoming_datagram_stream_receive(udp_borrow_incoming_datagram_stream_t self, uint64_t max_results, udp_list_incoming_datagram_t *ret, udp_error_code_t *err);
extern udp_own_pollable_t udp_method_incoming_datagram_stream_subscribe(udp_borrow_incoming_datagram_stream_t self);
extern bool udp_method_outgoing_datagram_stream_check_send(udp_borrow_outgoing_datagram_stream_t self, uint64_t *ret, udp_error_code_t *err);
extern bool udp_method_outgoing_datagram_stream_send(udp_borrow_outgoing_datagram_stream_t self, udp_list_outgoing_datagram_t *datagrams, uint64_t *ret, udp_error_code_t *err);
extern udp_own_pollable_t udp_method_outgoing_datagram_stream_subscribe(udp_borrow_outgoing_datagram_stream_t self);

// Imported Functions from `wasi:sockets/udp-create-socket@0.2.0`
extern bool udp_create_socket_create_udp_socket(udp_create_socket_ip_address_family_t address_family, udp_create_socket_own_udp_socket_t *ret, udp_create_socket_error_code_t *err);

// Imported Functions from `wasi:sockets/tcp@0.2.0`
extern bool tcp_method_tcp_socket_start_bind(tcp_borrow_tcp_socket_t self, tcp_borrow_network_t network, tcp_ip_socket_address_t *local_address, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_finish_bind(tcp_borrow_tcp_socket_t self, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_start_connect(tcp_borrow_tcp_socket_t self, tcp_borrow_network_t network, tcp_ip_socket_address_t *remote_address, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_finish_connect(tcp_borrow_tcp_socket_t self, tcp_tuple2_own_input_stream_own_output_stream_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_start_listen(tcp_borrow_tcp_socket_t self, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_finish_listen(tcp_borrow_tcp_socket_t self, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_accept(tcp_borrow_tcp_socket_t self, tcp_tuple3_own_tcp_socket_own_input_stream_own_output_stream_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_local_address(tcp_borrow_tcp_socket_t self, tcp_ip_socket_address_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_remote_address(tcp_borrow_tcp_socket_t self, tcp_ip_socket_address_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_is_listening(tcp_borrow_tcp_socket_t self);
extern tcp_ip_address_family_t tcp_method_tcp_socket_address_family(tcp_borrow_tcp_socket_t self);
extern bool tcp_method_tcp_socket_set_listen_backlog_size(tcp_borrow_tcp_socket_t self, uint64_t value, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_keep_alive_enabled(tcp_borrow_tcp_socket_t self, bool *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_set_keep_alive_enabled(tcp_borrow_tcp_socket_t self, bool value, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_keep_alive_idle_time(tcp_borrow_tcp_socket_t self, tcp_duration_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_set_keep_alive_idle_time(tcp_borrow_tcp_socket_t self, tcp_duration_t value, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_keep_alive_interval(tcp_borrow_tcp_socket_t self, tcp_duration_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_set_keep_alive_interval(tcp_borrow_tcp_socket_t self, tcp_duration_t value, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_keep_alive_count(tcp_borrow_tcp_socket_t self, uint32_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_set_keep_alive_count(tcp_borrow_tcp_socket_t self, uint32_t value, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_hop_limit(tcp_borrow_tcp_socket_t self, uint8_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_set_hop_limit(tcp_borrow_tcp_socket_t self, uint8_t value, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_receive_buffer_size(tcp_borrow_tcp_socket_t self, uint64_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_set_receive_buffer_size(tcp_borrow_tcp_socket_t self, uint64_t value, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_send_buffer_size(tcp_borrow_tcp_socket_t self, uint64_t *ret, tcp_error_code_t *err);
extern bool tcp_method_tcp_socket_set_send_buffer_size(tcp_borrow_tcp_socket_t self, uint64_t value, tcp_error_code_t *err);
extern tcp_own_pollable_t tcp_method_tcp_socket_subscribe(tcp_borrow_tcp_socket_t self);
extern bool tcp_method_tcp_socket_shutdown(tcp_borrow_tcp_socket_t self, tcp_shutdown_type_t shutdown_type, tcp_error_code_t *err);

// Imported Functions from `wasi:sockets/tcp-create-socket@0.2.0`
extern bool tcp_create_socket_create_tcp_socket(tcp_create_socket_ip_address_family_t address_family, tcp_create_socket_own_tcp_socket_t *ret, tcp_create_socket_error_code_t *err);

// Imported Functions from `wasi:sockets/ip-name-lookup@0.2.0`
extern bool ip_name_lookup_method_resolve_address_stream_resolve_next_address(ip_name_lookup_borrow_resolve_address_stream_t self, ip_name_lookup_option_ip_address_t *ret, ip_name_lookup_error_code_t *err);
extern ip_name_lookup_own_pollable_t ip_name_lookup_method_resolve_address_stream_subscribe(ip_name_lookup_borrow_resolve_address_stream_t self);
extern bool ip_name_lookup_resolve_addresses(ip_name_lookup_borrow_network_t network, wasip2_string_t *name, ip_name_lookup_own_resolve_address_stream_t *ret, ip_name_lookup_error_code_t *err);

// Imported Functions from `wasi:random/random@0.2.0`
extern void random_get_random_bytes(uint64_t len, wasip2_list_u8_t *ret);
extern uint64_t random_get_random_u64(void);

// Imported Functions from `wasi:random/insecure@0.2.0`
extern void random_insecure_get_insecure_random_bytes(uint64_t len, wasip2_list_u8_t *ret);
extern uint64_t random_insecure_get_insecure_random_u64(void);

// Imported Functions from `wasi:random/insecure-seed@0.2.0`
extern void random_insecure_seed_insecure_seed(wasip2_tuple2_u64_u64_t *ret);

// Helper Functions

void wasip2_tuple2_string_string_free(wasip2_tuple2_string_string_t *ptr);

void wasip2_list_tuple2_string_string_free(wasip2_list_tuple2_string_string_t *ptr);

void wasip2_list_string_free(wasip2_list_string_t *ptr);

void wasip2_option_string_free(wasip2_option_string_t *ptr);

void exit_result_void_void_free(exit_result_void_void_t *ptr);

extern void io_error_error_drop_own(io_error_own_error_t handle);

extern io_error_borrow_error_t io_error_borrow_error(io_error_own_error_t handle);

extern void poll_pollable_drop_own(poll_own_pollable_t handle);

extern poll_borrow_pollable_t poll_borrow_pollable(poll_own_pollable_t handle);

void poll_list_borrow_pollable_free(poll_list_borrow_pollable_t *ptr);

void wasip2_list_u32_free(wasip2_list_u32_t *ptr);

void streams_stream_error_free(streams_stream_error_t *ptr);

extern void streams_input_stream_drop_own(streams_own_input_stream_t handle);

extern streams_borrow_input_stream_t streams_borrow_input_stream(streams_own_input_stream_t handle);

extern void streams_output_stream_drop_own(streams_own_output_stream_t handle);

extern streams_borrow_output_stream_t streams_borrow_output_stream(streams_own_output_stream_t handle);

void wasip2_list_u8_free(wasip2_list_u8_t *ptr);

void streams_result_list_u8_stream_error_free(streams_result_list_u8_stream_error_t *ptr);

void streams_result_u64_stream_error_free(streams_result_u64_stream_error_t *ptr);

void streams_result_void_stream_error_free(streams_result_void_stream_error_t *ptr);

extern void terminal_input_terminal_input_drop_own(terminal_input_own_terminal_input_t handle);

extern terminal_input_borrow_terminal_input_t terminal_input_borrow_terminal_input(terminal_input_own_terminal_input_t handle);

extern void terminal_output_terminal_output_drop_own(terminal_output_own_terminal_output_t handle);

extern terminal_output_borrow_terminal_output_t terminal_output_borrow_terminal_output(terminal_output_own_terminal_output_t handle);

void terminal_stdin_option_own_terminal_input_free(terminal_stdin_option_own_terminal_input_t *ptr);

void terminal_stdout_option_own_terminal_output_free(terminal_stdout_option_own_terminal_output_t *ptr);

void terminal_stderr_option_own_terminal_output_free(terminal_stderr_option_own_terminal_output_t *ptr);

void filesystem_option_datetime_free(filesystem_option_datetime_t *ptr);

void filesystem_descriptor_stat_free(filesystem_descriptor_stat_t *ptr);

void filesystem_new_timestamp_free(filesystem_new_timestamp_t *ptr);

void filesystem_directory_entry_free(filesystem_directory_entry_t *ptr);

extern void filesystem_descriptor_drop_own(filesystem_own_descriptor_t handle);

extern filesystem_borrow_descriptor_t filesystem_borrow_descriptor(filesystem_own_descriptor_t handle);

extern void filesystem_directory_entry_stream_drop_own(filesystem_own_directory_entry_stream_t handle);

extern filesystem_borrow_directory_entry_stream_t filesystem_borrow_directory_entry_stream(filesystem_own_directory_entry_stream_t handle);

void filesystem_result_own_input_stream_error_code_free(filesystem_result_own_input_stream_error_code_t *ptr);

void filesystem_result_own_output_stream_error_code_free(filesystem_result_own_output_stream_error_code_t *ptr);

void filesystem_result_void_error_code_free(filesystem_result_void_error_code_t *ptr);

void filesystem_result_descriptor_flags_error_code_free(filesystem_result_descriptor_flags_error_code_t *ptr);

void filesystem_result_descriptor_type_error_code_free(filesystem_result_descriptor_type_error_code_t *ptr);

void filesystem_result_tuple2_list_u8_bool_error_code_free(filesystem_result_tuple2_list_u8_bool_error_code_t *ptr);

void filesystem_result_filesize_error_code_free(filesystem_result_filesize_error_code_t *ptr);

void filesystem_result_own_directory_entry_stream_error_code_free(filesystem_result_own_directory_entry_stream_error_code_t *ptr);

void filesystem_result_descriptor_stat_error_code_free(filesystem_result_descriptor_stat_error_code_t *ptr);

void filesystem_result_own_descriptor_error_code_free(filesystem_result_own_descriptor_error_code_t *ptr);

void filesystem_result_string_error_code_free(filesystem_result_string_error_code_t *ptr);

void filesystem_result_metadata_hash_value_error_code_free(filesystem_result_metadata_hash_value_error_code_t *ptr);

void filesystem_option_directory_entry_free(filesystem_option_directory_entry_t *ptr);

void filesystem_result_option_directory_entry_error_code_free(filesystem_result_option_directory_entry_error_code_t *ptr);

void filesystem_option_error_code_free(filesystem_option_error_code_t *ptr);

void filesystem_preopens_tuple2_own_descriptor_string_free(filesystem_preopens_tuple2_own_descriptor_string_t *ptr);

void filesystem_preopens_list_tuple2_own_descriptor_string_free(filesystem_preopens_list_tuple2_own_descriptor_string_t *ptr);

extern void network_network_drop_own(network_own_network_t handle);

extern network_borrow_network_t network_borrow_network(network_own_network_t handle);

void network_ip_address_free(network_ip_address_t *ptr);

void network_ip_socket_address_free(network_ip_socket_address_t *ptr);

void udp_ip_socket_address_free(udp_ip_socket_address_t *ptr);

void udp_incoming_datagram_free(udp_incoming_datagram_t *ptr);

void udp_option_ip_socket_address_free(udp_option_ip_socket_address_t *ptr);

void udp_outgoing_datagram_free(udp_outgoing_datagram_t *ptr);

extern void udp_udp_socket_drop_own(udp_own_udp_socket_t handle);

extern udp_borrow_udp_socket_t udp_borrow_udp_socket(udp_own_udp_socket_t handle);

extern void udp_incoming_datagram_stream_drop_own(udp_own_incoming_datagram_stream_t handle);

extern udp_borrow_incoming_datagram_stream_t udp_borrow_incoming_datagram_stream(udp_own_incoming_datagram_stream_t handle);

extern void udp_outgoing_datagram_stream_drop_own(udp_own_outgoing_datagram_stream_t handle);

extern udp_borrow_outgoing_datagram_stream_t udp_borrow_outgoing_datagram_stream(udp_own_outgoing_datagram_stream_t handle);

void udp_result_void_error_code_free(udp_result_void_error_code_t *ptr);

void udp_result_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_error_code_free(udp_result_tuple2_own_incoming_datagram_stream_own_outgoing_datagram_stream_error_code_t *ptr);

void udp_result_ip_socket_address_error_code_free(udp_result_ip_socket_address_error_code_t *ptr);

void udp_result_u8_error_code_free(udp_result_u8_error_code_t *ptr);

void udp_result_u64_error_code_free(udp_result_u64_error_code_t *ptr);

void udp_list_incoming_datagram_free(udp_list_incoming_datagram_t *ptr);

void udp_result_list_incoming_datagram_error_code_free(udp_result_list_incoming_datagram_error_code_t *ptr);

void udp_list_outgoing_datagram_free(udp_list_outgoing_datagram_t *ptr);

void udp_create_socket_result_own_udp_socket_error_code_free(udp_create_socket_result_own_udp_socket_error_code_t *ptr);

void tcp_ip_socket_address_free(tcp_ip_socket_address_t *ptr);

extern void tcp_tcp_socket_drop_own(tcp_own_tcp_socket_t handle);

extern tcp_borrow_tcp_socket_t tcp_borrow_tcp_socket(tcp_own_tcp_socket_t handle);

void tcp_result_void_error_code_free(tcp_result_void_error_code_t *ptr);

void tcp_result_tuple2_own_input_stream_own_output_stream_error_code_free(tcp_result_tuple2_own_input_stream_own_output_stream_error_code_t *ptr);

void tcp_result_tuple3_own_tcp_socket_own_input_stream_own_output_stream_error_code_free(tcp_result_tuple3_own_tcp_socket_own_input_stream_own_output_stream_error_code_t *ptr);

void tcp_result_ip_socket_address_error_code_free(tcp_result_ip_socket_address_error_code_t *ptr);

void tcp_result_bool_error_code_free(tcp_result_bool_error_code_t *ptr);

void tcp_result_duration_error_code_free(tcp_result_duration_error_code_t *ptr);

void tcp_result_u32_error_code_free(tcp_result_u32_error_code_t *ptr);

void tcp_result_u8_error_code_free(tcp_result_u8_error_code_t *ptr);

void tcp_result_u64_error_code_free(tcp_result_u64_error_code_t *ptr);

void tcp_create_socket_result_own_tcp_socket_error_code_free(tcp_create_socket_result_own_tcp_socket_error_code_t *ptr);

void ip_name_lookup_ip_address_free(ip_name_lookup_ip_address_t *ptr);

extern void ip_name_lookup_resolve_address_stream_drop_own(ip_name_lookup_own_resolve_address_stream_t handle);

extern ip_name_lookup_borrow_resolve_address_stream_t ip_name_lookup_borrow_resolve_address_stream(ip_name_lookup_own_resolve_address_stream_t handle);

void ip_name_lookup_option_ip_address_free(ip_name_lookup_option_ip_address_t *ptr);

void ip_name_lookup_result_option_ip_address_error_code_free(ip_name_lookup_result_option_ip_address_error_code_t *ptr);

void ip_name_lookup_result_own_resolve_address_stream_error_code_free(ip_name_lookup_result_own_resolve_address_stream_error_code_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void wasip2_string_set(wasip2_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void wasip2_string_dup(wasip2_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void wasip2_string_dup_n(wasip2_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void wasip2_string_free(wasip2_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
