package wasi-libc:wasip3;

world wasip3 {
    include wasi:cli/command@0.3.0-rc-2026-01-06;
    include wasi:clocks/imports@0.3.0-rc-2026-01-06;
    include wasi:filesystem/imports@0.3.0-rc-2026-01-06;
    include wasi:http/middleware@0.3.0-rc-2026-01-06;
    include wasi:random/imports@0.3.0-rc-2026-01-06;
    include wasi:sockets/imports@0.3.0-rc-2026-01-06;
}
